name: CI-quick-check

on:
  workflow_dispatch:
  push:
    branches-ignore: main

jobs:
  cache-restore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache/restore@v3
        with:
          path: random/path
          key: execution-dependencies-90c4abcba53dc1c94c5880b0603e17ee