name: CI-quick-check

on:
  workflow_dispatch:
  push:
    branches-ignore: main

jobs:
  cache-restore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache/restore@v3
        with:
          path: /home/runner/.gradle/caches/modules-*/files-*/*/*/*/*
          key: action-inputs-dependencies-6ebdc5f61955f5b969df7a1bbe3b344e
